import { formatMoney } from "@/lib/money";
import type { InsightType } from "@/lib/types";

/**
 * Insight drafts — the pure seam behind the persisted Insight records
 * (round 13). The live app's TransactionInsight rows are generated by an
 * external backend process; the clone's equivalent generates deterministic
 * drafts from the current-month facts (with the LLM polishing at persist
 * time in the route) ONCE when the table is empty. The fields mirror the
 * live record set the card anatomy renders: insight_type, title,
 * description, suggested_action, confidence_score, category.
 */

/** The live's five insight_type values (badge text renders the raw id). */
export const INSIGHT_TYPES = ["anomaly", "alert", "trend", "opportunity", "prediction"] as const;

export interface InsightDraft {
  insightType: InsightType;
  title: string;
  description: string;
  suggestedAction?: string;
  confidenceScore: number;
  category?: string;
}

export interface InsightDraftInput {
  monthlyIncomeMinor: number;
  monthlyExpensesMinor: number;
  topCategory: { label: string; amountMinor: number } | null;
  savingsRate: number;
  currency: string;
  budgetNotes: string[];
}

/** Deterministic confidence per draft kind (stable across requests). */
const CONFIDENCE = {
  savings: 0.9,
  topCategory: 0.85,
  overspend: 0.75,
  budgetWatch: 0.8,
} as const;

export function buildInsightDrafts(input: InsightDraftInput): InsightDraft[] {
  const { monthlyIncomeMinor, monthlyExpensesMinor, topCategory, savingsRate, currency, budgetNotes } = input;
  const drafts: InsightDraft[] = [];

  if (monthlyIncomeMinor > 0) {
    const onTrack = savingsRate >= 20;
    drafts.push({
      insightType: onTrack ? "opportunity" : "trend",
      title: "Savings rate check",
      description:
        `You are currently saving ${savingsRate.toFixed(1)}% of your income this month. ` +
        (onTrack
          ? "That is at or above the 20% benchmark, keep it up."
          : "The 50/30/20 rule suggests targeting 20% for savings."),
      suggestedAction: onTrack
        ? undefined
        : "Trim wants spending this month to move your savings rate toward the 20% benchmark.",
      confidenceScore: CONFIDENCE.savings,
    });
  }

  if (topCategory) {
    drafts.push({
      insightType: "trend",
      title: "Top spending category",
      description:
        `${topCategory.label} is your largest category at ${formatMoney(topCategory.amountMinor, { currency })} this month.`,
      confidenceScore: CONFIDENCE.topCategory,
      category: topCategory.label,
    });
  }

  if (monthlyExpensesMinor > monthlyIncomeMinor) {
    drafts.push({
      insightType: "alert",
      title: "Spending exceeds income",
      description:
        `Expenses (${formatMoney(monthlyExpensesMinor, { currency })}) exceed income (${formatMoney(monthlyIncomeMinor, { currency })}) this month.`,
      suggestedAction: "Review discretionary categories before the month closes.",
      confidenceScore: CONFIDENCE.overspend,
    });
  }

  if (budgetNotes.length > 0 && drafts.length < 3) {
    drafts.push({
      insightType: "alert",
      title: "Budget watch",
      description: budgetNotes.join(" "),
      confidenceScore: CONFIDENCE.budgetWatch,
      category: "Needs",
    });
  }

  return drafts.slice(0, 3);
}

/**
 * Join LLM-polished entries back onto their drafts. The polish prompt pins
 * the order ("Keep the same order"), so the join is POSITIONAL: each valid
 * entry inherits its draft's insightType (when invalid/missing),
 * suggestedAction (when omitted), and confidenceScore + category — the
 * LLM rewrites titles, so a title-keyed join silently loses those fields
 * (caught by the round-13 E2E gate). Invalid entries are dropped without
 * shifting later positions; the set is capped at the draft count (the LLM
 * never adds records). Anything unusable returns the drafts untouched.
 */
export function mergePolishedDrafts(drafts: InsightDraft[], polished: unknown): InsightDraft[] {
  if (!Array.isArray(polished) || polished.length === 0) return drafts;
  const merged: InsightDraft[] = [];
  polished.slice(0, drafts.length).forEach((entry, index) => {
    if (typeof entry !== "object" || entry === null) return;
    const record = entry as Record<string, unknown>;
    if (typeof record.title !== "string" || record.title.length === 0) return;
    if (typeof record.description !== "string" || record.description.length === 0) return;
    const draft = drafts[index];
    if (!draft) return;
    const insightType = INSIGHT_TYPES.includes(record.insight_type as InsightType)
      ? (record.insight_type as InsightType)
      : draft.insightType;
    merged.push({
      insightType,
      title: record.title.slice(0, 80),
      description: record.description.slice(0, 400),
      suggestedAction:
        typeof record.suggested_action === "string" && record.suggested_action.length > 0
          ? record.suggested_action.slice(0, 200)
          : draft.suggestedAction,
      confidenceScore: draft.confidenceScore,
      category: typeof record.category === "string" ? record.category.slice(0, 40) : draft.category,
    });
  });
  return merged.length > 0 ? merged : drafts;
}
